services:
  - type: web
    name: gologchat-backend
    runtime: go
    rootDir: gologchat-backend
    buildCommand: go build -o server .
    startCommand: ./server
    plan: free
    envVars:
      - key: PORT
        value: "10000"
